# Make sure that the additional_dependencies here match requirements.txt

ci:
    autofix_prs: false
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
    -   id: mypy
        additional_dependencies:
          - httpx~=0.25.0
          - XlsxWriter~=3.1.4
          - isoweek~=1.3.3
          - pydantic~=2.4.2
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    -   id: pyupgrade
        args:
          - --py311-plus
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.287'
    hooks:
    -   id: ruff
        additional_dependencies:
          - httpx~=0.25.0
          - XlsxWriter~=3.1.4
          - isoweek~=1.3.3
          - pydantic~=2.4.2
